name: dl2
channels:
  - apple
  - defaults
dependencies:
  - _anaconda_depends=2023.06
  - abseil-cpp=20211102.0
  - aiobotocore=2.5.0
  - aiofiles=22.1.0
  - aiohttp=3.8.3
  - aioitertools=0.7.1
  - aiosignal=1.2.0
  - aiosqlite=0.18.0
  - alabaster=0.7.12
  - anaconda=custom
  - anyio=3.5.0
  - appdirs=1.4.4
  - applaunchservices=0.3.0
  - appnope=0.1.2
  - appscript=1.1.2
  - argon2-cffi=21.3.0
  - argon2-cffi-bindings=21.2.0
  - arrow=1.2.3
  - arrow-cpp=11.0.0
  - astroid=2.14.2
  - astropy=5.1
  - asttokens=2.0.5
  - async-timeout=4.0.2
  - atomicwrites=1.4.0
  - attrs=22.1.0
  - automat=20.2.0
  - autopep8=1.6.0
  - aws-c-common=0.6.8
  - aws-c-event-stream=0.1.6
  - aws-checksums=0.1.11
  - aws-sdk-cpp=1.8.185
  - babel=2.11.0
  - backcall=0.2.0
  - bcrypt=3.2.0
  - beautifulsoup4=4.12.2
  - binaryornot=0.4.4
  - black=23.3.0
  - blas=1.0
  - bleach=4.1.0
  - blosc=1.21.3
  - bokeh=3.1.1
  - boost-cpp=1.73.0
  - botocore=1.29.76
  - bottleneck=1.3.5
  - brotli=1.0.9
  - brotli-bin=1.0.9
  - brotlipy=0.7.0
  - brunsli=0.1
  - bzip2=1.0.8
  - c-ares=1.19.0
  - c-blosc2=2.8.0
  - ca-certificates=2023.05.30
  - certifi=2023.5.7
  - cffi=1.15.1
  - cfitsio=3.470
  - chardet=4.0.0
  - charls=2.2.0
  - charset-normalizer=2.0.4
  - click=8.0.4
  - cloudpickle=2.2.1
  - colorama=0.4.6
  - colorcet=3.0.1
  - comm=0.1.2
  - constantly=15.1.0
  - contourpy=1.0.5
  - cookiecutter=1.7.3
  - cryptography=39.0.1
  - cssselect=1.1.0
  - curl=8.1.1
  - cycler=0.11.0
  - cytoolz=0.12.0
  - dask=2023.6.0
  - dask-core=2023.6.0
  - datasets=2.12.0
  - datashader=0.15.0
  - datashape=0.5.4
  - debugpy=1.5.1
  - decorator=5.1.1
  - defusedxml=0.7.1
  - diff-match-patch=20200713
  - dill=0.3.6
  - distributed=2023.6.0
  - docstring-to-markdown=0.11
  - docutils=0.18.1
  - entrypoints=0.4
  - et_xmlfile=1.1.0
  - exceptiongroup=1.0.4
  - executing=0.8.3
  - filelock=3.9.0
  - flake8=6.0.0
  - flask=2.2.2
  - fonttools=4.25.0
  - freetype=2.12.1
  - frozenlist=1.3.3
  - fsspec=2023.4.0
  - gensim=4.3.0
  - gettext=0.21.0
  - gflags=2.2.2
  - giflib=5.2.1
  - glib=2.69.1
  - glog=0.5.0
  - gmp=6.2.1
  - gmpy2=2.1.2
  - greenlet=2.0.1
  - grpc-cpp=1.48.2
  - grpcio=1.48.2
  - gst-plugins-base=1.14.1
  - gstreamer=1.14.1
  - h5py=3.6.0
  - hdf5=1.12.1
  - heapdict=1.0.1
  - holoviews=1.16.2
  - huggingface_hub=0.15.1
  - hvplot=0.8.4
  - hyperlink=21.0.0
  - icu=68.1
  - idna=3.4
  - imagecodecs=2021.8.26
  - imageio=2.31.1
  - imagesize=1.4.1
  - imbalanced-learn=0.10.1
  - importlib-metadata=6.0.0
  - importlib_metadata=6.0.0
  - incremental=21.3.0
  - inflection=0.5.1
  - iniconfig=1.1.1
  - intake=0.6.8
  - intervaltree=3.1.0
  - ipykernel=6.19.2
  - ipython=8.12.0
  - ipython_genutils=0.2.0
  - ipywidgets=8.0.4
  - isort=5.9.3
  - itemadapter=0.3.0
  - itemloaders=1.0.4
  - itsdangerous=2.0.1
  - jaraco.classes=3.2.1
  - jedi=0.18.1
  - jellyfish=0.9.0
  - jinja2=3.1.2
  - jinja2-time=0.2.0
  - jmespath=0.10.0
  - joblib=1.2.0
  - jpeg=9e
  - jq=1.6
  - json5=0.9.6
  - jsonschema=4.17.3
  - jupyter=1.0.0
  - jupyter_client=8.1.0
  - jupyter_console=6.6.3
  - jupyter_core=5.3.0
  - jupyter_events=0.6.3
  - jupyter_server=2.5.0
  - jupyter_server_fileid=0.9.0
  - jupyter_server_terminals=0.4.4
  - jupyter_server_ydoc=0.8.0
  - jupyter_ydoc=0.2.4
  - jupyterlab=3.6.3
  - jupyterlab_pygments=0.1.2
  - jupyterlab_server=2.22.0
  - jupyterlab_widgets=3.0.5
  - jxrlib=1.1
  - keyring=23.13.1
  - kiwisolver=1.4.4
  - krb5=1.20.1
  - lazy-object-proxy=1.6.0
  - lazy_loader=0.2
  - lcms2=2.12
  - lerc=3.0
  - libaec=1.0.4
  - libboost=1.73.0
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libcurl=8.1.1
  - libcxx=14.0.6
  - libdeflate=1.17
  - libedit=3.1.20221030
  - libev=4.33
  - libevent=2.1.12
  - libffi=3.4.4
  - libgfortran=5.0.0
  - libgfortran5=11.3.0
  - libiconv=1.16
  - libllvm12=12.0.0
  - libllvm14=14.0.6
  - libnghttp2=1.52.0
  - libopenblas=0.3.21
  - libpng=1.6.39
  - libpq=12.15
  - libprotobuf=3.20.3
  - libsodium=1.0.18
  - libspatialindex=1.9.3
  - libssh2=1.10.0
  - libthrift=0.15.0
  - libtiff=4.5.0
  - libuv=1.44.2
  - libwebp=1.2.4
  - libwebp-base=1.2.4
  - libxml2=2.10.3
  - libxslt=1.1.37
  - libzopfli=1.0.3
  - linkify-it-py=2.0.0
  - llvm-openmp=14.0.6
  - llvmlite=0.40.0
  - locket=1.0.0
  - lxml=4.9.2
  - lz4=4.3.2
  - lz4-c=1.9.4
  - lzo=2.10
  - markdown=3.4.1
  - markdown-it-py=2.2.0
  - markupsafe=2.1.1
  - matplotlib=3.7.1
  - matplotlib-base=3.7.1
  - matplotlib-inline=0.1.6
  - mccabe=0.7.0
  - mdit-py-plugins=0.3.0
  - mdurl=0.1.0
  - mistune=0.8.4
  - more-itertools=8.12.0
  - mpc=1.1.0
  - mpfr=4.0.2
  - msgpack-python=1.0.3
  - multidict=6.0.2
  - multipledispatch=0.6.0
  - multiprocess=0.70.14
  - munkres=1.1.4
  - mypy_extensions=0.4.3
  - nbclassic=0.5.5
  - nbclient=0.5.13
  - nbconvert=6.5.4
  - nbformat=5.7.0
  - ncurses=6.4
  - nest-asyncio=1.5.6
  - networkx=2.8.4
  - ninja=1.10.2
  - ninja-base=1.10.2
  - nltk=3.7
  - notebook=6.5.4
  - notebook-shim=0.2.2
  - nspr=4.35
  - nss=3.89.1
  - numba=0.57.0
  - numexpr=2.8.4
  - numpydoc=1.5.0
  - oniguruma=6.9.7.1
  - openjpeg=2.3.0
  - openpyxl=3.0.10
  - openssl=3.0.9
  - orc=1.7.4
  - packaging=23.0
  - pandas=1.5.3
  - pandocfilters=1.5.0
  - panel=1.1.0
  - param=1.13.0
  - parsel=1.6.0
  - parso=0.8.3
  - partd=1.2.0
  - pathspec=0.10.3
  - patsy=0.5.3
  - pcre=8.45
  - pep8=1.7.1
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pillow=9.4.0
  - pip=23.1.2
  - platformdirs=2.5.2
  - plotly=5.9.0
  - pluggy=1.0.0
  - ply=3.11
  - pooch=1.4.0
  - poyo=0.5.0
  - prometheus_client=0.14.1
  - prompt-toolkit=3.0.36
  - prompt_toolkit=3.0.36
  - protego=0.1.16
  - psutil=5.9.0
  - ptyprocess=0.7.0
  - pure_eval=0.2.2
  - py-cpuinfo=8.0.0
  - pyarrow=11.0.0
  - pyasn1=0.4.8
  - pyasn1-modules=0.2.8
  - pycodestyle=2.10.0
  - pycparser=2.21
  - pyct=0.5.0
  - pycurl=7.45.2
  - pydispatcher=2.0.5
  - pydocstyle=6.3.0
  - pyerfa=2.0.0
  - pyflakes=3.0.1
  - pygments=2.15.1
  - pylint=2.16.2
  - pylint-venv=2.3.0
  - pyls-spyder=0.4.0
  - pyobjc-framework-coreservices=9.0
  - pyobjc-framework-fsevents=9.0
  - pyodbc=4.0.34
  - pyopenssl=23.0.0
  - pyparsing=3.0.9
  - pyqt=5.15.7
  - pyqtwebengine=5.15.7
  - pyrsistent=0.18.0
  - pysocks=1.7.1
  - pytables=3.8.0
  - pytest=7.3.1
  - python=3.10.11
  - python-dateutil=2.8.2
  - python-fastjsonschema=2.16.2
  - python-json-logger=2.0.7
  - python-lmdb=1.4.1
  - python-lsp-black=1.2.1
  - python-lsp-jsonrpc=1.0.0
  - python-lsp-server=1.7.2
  - python-slugify=5.0.2
  - python-snappy=0.6.1
  - python-xxhash=2.0.2
  - python.app=3
  - pytoolconfig=1.2.5
  - pytorch=2.0.1
  - pytz=2022.7
  - pyviz_comms=2.3.0
  - pywavelets=1.4.1
  - pyyaml=6.0
  - pyzmq=25.1.0
  - qdarkstyle=3.0.2
  - qstylizer=0.2.2
  - qt-main=5.15.2
  - qt-webengine=5.15.9
  - qtawesome=1.2.2
  - qtconsole=5.4.2
  - qtpy=2.2.0
  - qtwebkit=5.212
  - queuelib=1.5.0
  - re2=2022.04.01
  - readline=8.2
  - regex=2022.7.9
  - requests=2.29.0
  - requests-file=1.5.1
  - responses=0.13.3
  - rfc3339-validator=0.1.4
  - rfc3986-validator=0.1.1
  - rope=1.7.0
  - rtree=1.0.1
  - s3fs=2023.4.0
  - sacremoses=0.0.43
  - scikit-image=0.20.0
  - scikit-learn=1.2.2
  - scipy=1.10.1
  - scrapy=2.8.0
  - seaborn=0.12.2
  - send2trash=1.8.0
  - service_identity=18.1.0
  - setuptools=67.8.0
  - sip=6.6.2
  - sleef=3.5.1
  - smart_open=5.2.1
  - snappy=1.1.9
  - sniffio=1.2.0
  - snowballstemmer=2.2.0
  - sortedcontainers=2.4.0
  - soupsieve=2.4
  - sphinx=5.0.2
  - sphinxcontrib-applehelp=1.0.2
  - sphinxcontrib-devhelp=1.0.2
  - sphinxcontrib-htmlhelp=2.0.0
  - sphinxcontrib-jsmath=1.0.1
  - sphinxcontrib-qthelp=1.0.3
  - sphinxcontrib-serializinghtml=1.1.5
  - spyder=5.4.3
  - spyder-kernels=2.4.3
  - sqlalchemy=1.4.39
  - sqlite=3.41.2
  - stack_data=0.2.0
  - statsmodels=0.13.5
  - sympy=1.11.1
  - tabulate=0.8.10
  - tbb=2021.8.0
  - tbb4py=2021.8.0
  - tblib=1.7.0
  - tenacity=8.2.2
  - tensorflow-deps=2.9.0
  - terminado=0.17.1
  - text-unidecode=1.3
  - textdistance=4.2.1
  - threadpoolctl=2.2.0
  - three-merge=0.1.1
  - tifffile=2021.7.2
  - tinycss2=1.2.1
  - tk=8.6.12
  - tldextract=3.2.0
  - tokenizers=0.13.2
  - toml=0.10.2
  - tomli=2.0.1
  - tomlkit=0.11.1
  - toolz=0.12.0
  - tornado=6.2
  - tqdm=4.65.0
  - traitlets=5.7.1
  - transformers=4.29.2
  - twisted=22.10.0
  - typing-extensions=4.6.3
  - typing_extensions=4.6.3
  - tzdata=2023c
  - uc-micro-py=1.0.1
  - ujson=5.4.0
  - unidecode=1.2.0
  - unixodbc=2.3.11
  - urllib3=1.26.16
  - utf8proc=2.6.1
  - w3lib=1.21.0
  - watchdog=2.1.6
  - wcwidth=0.2.5
  - webencodings=0.5.1
  - websocket-client=0.58.0
  - werkzeug=2.2.3
  - whatthepatch=1.0.2
  - wheel=0.38.4
  - widgetsnbextension=4.0.5
  - wrapt=1.14.1
  - wurlitzer=3.0.2
  - xarray=2022.11.0
  - xlwings=0.29.1
  - xxhash=0.8.0
  - xyzservices=2022.9.0
  - xz=5.4.2
  - y-py=0.5.9
  - yaml=0.2.5
  - yapf=0.31.0
  - yarl=1.8.1
  - ypy-websocket=0.8.2
  - zeromq=4.3.4
  - zfp=0.5.5
  - zict=2.2.0
  - zipp=3.11.0
  - zlib=1.2.13
  - zlib-ng=2.0.7
  - zope=1.0
  - zope.interface=5.4.0
  - zstd=1.5.5
  - pip:
      - absl-py==1.4.0
      - astunparse==1.6.3
      - atomacos==3.3.0
      - backoff==2.2.1
      - bidict==0.22.1
      - cachetools==5.3.1
      - chromadb==0.3.26
      - clickhouse-connect==0.6.4
      - coloredlogs==15.0.1
      - comtypes==1.2.0
      - dataclasses-json==0.5.8
      - dnspython==2.3.0
      - duckdb==0.8.1
      - easyprocess==1.1
      - entrypoint2==1.1
      - eventlet==0.33.3
      - fastapi==0.98.0
      - flask-cors==4.0.0
      - flask-socketio==5.3.4
      - flatbuffers==1.12
      - future==0.18.3
      - gast==0.4.0
      - gevent==22.10.2
      - gevent-websocket==0.10.1
      - google-auth==2.20.0
      - google-auth-oauthlib==0.4.6
      - google-pasta==0.2.0
      - google-search-results==2.4.2
      - h11==0.14.0
      - hnswlib==0.7.0
      - httptools==0.5.0
      - humanfriendly==10.0
      - jax==0.4.12
      - keras==2.9.0
      - keras-preprocessing==1.1.2
      - langchain==0.0.215
      - langchainplus-sdk==0.0.17
      - libclang==16.0.0
      - marshmallow==3.19.0
      - marshmallow-enum==1.5.1
      - mediapipe-silicon==0.8.9
      - ml-dtypes==0.2.0
      - monotonic==1.6
      - mouseinfo==0.1.3
      - mpmath==1.2.1
      - mss==9.0.1
      - numpy==1.23.0
      - oauthlib==3.2.2
      - onnxruntime==1.15.1
      - openai==0.27.8
      - openapi-schema-pydantic==1.2.4
      - opencv-contrib-python==4.7.0.72
      - opencv-python==4.7.0.72
      - opt-einsum==3.3.0
      - overrides==7.3.1
      - posthog==3.0.1
      - protobuf==3.19.6
      - pulsar-client==3.2.0
      - pyautogui==0.9.41
      - pycaw==20230407
      - pydantic==1.10.9
      - pygetwindow==0.0.4
      - pymongo==4.4.0
      - pymsgbox==1.0.9
      - pyobjc-core==9.2
      - pyobjc-framework-applicationservices==9.2
      - pyobjc-framework-cocoa==9.2
      - pyobjc-framework-coretext==9.2
      - pyobjc-framework-quartz==9.2
      - pyperclip==1.8.2
      - pyqt5-sip==12.11.0
      - pyrect==0.2.0
      - pyscreenshot==3.1
      - pyscreeze==0.1.19
      - python-dotenv==1.0.0
      - python-engineio==4.4.1
      - python-socketio==5.8.0
      - pytweening==1.0.7
      - rdkit-pypi==2022.9.5
      - requests-oauthlib==1.3.1
      - rsa==4.9
      - rubicon-objc==0.4.6
      - semantic-version==2.10.0
      - setuptools-rust==1.6.0
      - six==1.15.0
      - sounddevice==0.4.6
      - starlette==0.27.0
      - tensorboard==2.9.1
      - tensorboard-data-server==0.6.1
      - tensorboard-plugin-wit==1.8.1
      - tensorflow-estimator==2.9.0
      - tensorflow-macos==2.9.0
      - tensorflow-metal==0.5.0
      - termcolor==2.3.0
      - tiktoken==0.4.0
      - typing-inspect==0.9.0
      - uvicorn==0.22.0
      - uvloop==0.17.0
      - watchfiles==0.19.0
      - websockets==11.0.3
      - zope-event==5.0
      - zstandard==0.21.0
